FROM microsoft/aspnetcore-build:2.0.0-stretch

# Step 1: Install mono
RUN set -x \
    && apt-get update \
    && apt-get install -y mono-complete bzip2 --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Step 2: Install yarn
RUN curl -o- -L https://yarnpkg.com/install.sh | bash

# Step 3: Warm up yarn
WORKDIR /project

COPY package.json .

ENV PATH "/root/.yarn/bin:$PATH"
RUN yarn install