FROM microsoft/aspnetcore-build:2.0.0-stretch

# Step 1: Install mono
RUN set -x \
    && apt-get update \
    && apt-get install -y mono-complete \
    && rm -rf /var/lib/apt/lists/*

# Step 2: Warm up npm
WORKDIR /project

COPY package-lock.json .
COPY package.json .

RUN npm install